name: Java CI

on:
  workflow_dispatch: # We can run this workflow manually
    inputs:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 16
      uses: actions/setup-java@master
      with:
        java-version: 16
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: Upload target folder
      uses: actions/upload-artifact@v2
      with:
        name: target
        path: |
          ${{ github.workspace }}/target
          ${{ github.workspace }}/reports
